//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.07.22 at 04:12:51 PM CEST 
//


package com.videopolis.smaug.common.model.impl.xml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element name="categoryCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="groupingStrategy" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="urlCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="urlSeoTranslation" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="range" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element ref="{http://www.tvtrip.com/smaug/SearchReference}scopes" minOccurs="0"/>
 *       &lt;/all>
 *       &lt;attribute name="filterOnly" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *       &lt;attribute name="facetCache" type="{http://www.w3.org/2001/XMLSchema}boolean" default="true" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {

})
@XmlRootElement(name = "facetCategory")
public class FacetCategory {

    @XmlElement(required = true)
    protected String categoryCode;
    @XmlElement(required = true)
    protected String groupingStrategy;
    @XmlElement(required = true)
    protected String urlCode;
    protected boolean urlSeoTranslation;
    @XmlElement(defaultValue = "false")
    protected Boolean range;
    protected Scopes scopes;
    @XmlAttribute
    protected Boolean filterOnly;
    @XmlAttribute
    protected Boolean facetCache;

    /**
     * Gets the value of the categoryCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCategoryCode() {
        return categoryCode;
    }

    /**
     * Sets the value of the categoryCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCategoryCode(String value) {
        this.categoryCode = value;
    }

    /**
     * Gets the value of the groupingStrategy property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGroupingStrategy() {
        return groupingStrategy;
    }

    /**
     * Sets the value of the groupingStrategy property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGroupingStrategy(String value) {
        this.groupingStrategy = value;
    }

    /**
     * Gets the value of the urlCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUrlCode() {
        return urlCode;
    }

    /**
     * Sets the value of the urlCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUrlCode(String value) {
        this.urlCode = value;
    }

    /**
     * Gets the value of the urlSeoTranslation property.
     * 
     */
    public boolean isUrlSeoTranslation() {
        return urlSeoTranslation;
    }

    /**
     * Sets the value of the urlSeoTranslation property.
     * 
     */
    public void setUrlSeoTranslation(boolean value) {
        this.urlSeoTranslation = value;
    }

    /**
     * Gets the value of the range property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isRange() {
        return range;
    }

    /**
     * Sets the value of the range property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setRange(Boolean value) {
        this.range = value;
    }

    /**
     * Gets the value of the scopes property.
     * 
     * @return
     *     possible object is
     *     {@link Scopes }
     *     
     */
    public Scopes getScopes() {
        return scopes;
    }

    /**
     * Sets the value of the scopes property.
     * 
     * @param value
     *     allowed object is
     *     {@link Scopes }
     *     
     */
    public void setScopes(Scopes value) {
        this.scopes = value;
    }

    /**
     * Gets the value of the filterOnly property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isFilterOnly() {
        if (filterOnly == null) {
            return false;
        } else {
            return filterOnly;
        }
    }

    /**
     * Sets the value of the filterOnly property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setFilterOnly(Boolean value) {
        this.filterOnly = value;
    }

    /**
     * Gets the value of the facetCache property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isFacetCache() {
        if (facetCache == null) {
            return true;
        } else {
            return facetCache;
        }
    }

    /**
     * Sets the value of the facetCache property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setFacetCache(Boolean value) {
        this.facetCache = value;
    }

}
