//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.07.22 at 04:12:51 PM CEST 
//


package com.videopolis.smaug.common.model.impl.xml;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.videopolis.smaug.common.model.impl.xml package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.videopolis.smaug.common.model.impl.xml
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link FacetCategory }
     * 
     */
    public FacetCategory createFacetCategory() {
        return new FacetCategory();
    }

    /**
     * Create an instance of {@link Sorter }
     * 
     */
    public Sorter createSorter() {
        return new Sorter();
    }

    /**
     * Create an instance of {@link Scopes }
     * 
     */
    public Scopes createScopes() {
        return new Scopes();
    }

    /**
     * Create an instance of {@link Sorters }
     * 
     */
    public Sorters createSorters() {
        return new Sorters();
    }

    /**
     * Create an instance of {@link FacetCategories }
     * 
     */
    public FacetCategories createFacetCategories() {
        return new FacetCategories();
    }

}
